#!/usr/bin/env python

import sys
import json
import wikidata_suggest

if __name__ == "__main__":
    if len(sys.argv) > 1:
        name = ' '.join(sys.argv[1:])
    else:
        name = raw_input("search for: ")
    try:
        result = wikidata_suggest.suggest(name)
        if result != None:
            print json.dumps(result, indent=2)
    except wikidata_suggest.Quit:
        pass
